/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-04-27 19:33:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import room.Room;

public final class successful_005froom_005fbooking_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Hotel Rooms</title>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Noto+Sans&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("        .flexExpand {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h1 {\r\n");
      out.write("            font-family: 'Noto Sans', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #round1 {\r\n");
      out.write("            border-radius: 18px;\r\n");
      out.write("            width: 130px;\r\n");
      out.write("            height: 18px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #round2 {\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            height: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #check {\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            height: 25px;\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            margin: 8px 0;\r\n");
      out.write("            margin-left: 1.5rem;\r\n");
      out.write("            font-family: \"Noto Sans\", sans-serif;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=text] {\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            padding: 0.5em;\r\n");
      out.write("            margin: 8px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=submit] {\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            background-color: #AE91E5;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 14px 20px;\r\n");
      out.write("            margin: 8px 0;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-family: \"Noto Sans\", sans-serif;\r\n");
      out.write("            margin-left: 3em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown {\r\n");
      out.write("            height: 42px;\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            margin: 8px 0;\r\n");
      out.write("            margin-left: 4rem;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            font-family: \"Noto Sans\", sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button1 {\r\n");
      out.write("            letter-spacing: 0.13em;\r\n");
      out.write("            font-size: 0.8rem;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            padding: 0.75em;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            background-color: #AE91E5;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .center {\r\n");
      out.write("            width: 800px;\r\n");
      out.write("            height: 240px;\r\n");
      out.write("            background:rgba(0, 0, 0, 0.5);\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-family: 'Noto Sans', sans-serif;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #background img {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 45px;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            z-index: -1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button:hover {\r\n");
      out.write("            background-color: rgba(0, 0, 0, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button.outlined {\r\n");
      out.write("            border: 1px solid rgba(0, 0, 0, 0.5);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button.primary {\r\n");
      out.write("            background-color: #DAF7A6;\r\n");
      out.write("            color: black;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button.disabled {\r\n");
      out.write("            color: rgba(0, 0, 0, 0.35)\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-family: 'Noto Sans', sans-serif;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            font-size: small;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header {\r\n");
      out.write("            background-color: #AE91E5;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 0.5em 0.5rem;\r\n");
      out.write("            height: 45px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            border-bottom: 1px solid rgba(0, 0, 0, 0.5);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header h1 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            margin-left: 0.25em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header .button {\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        main {\r\n");
      out.write("            padding: 0.5em 0.5rem;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        footer {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            padding: 0.3rem;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            opacity: 0.80;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: medium;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 0.1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .popup {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            -webkit-user-select: none;\r\n");
      out.write("            -moz-user-select: none;\r\n");
      out.write("            -ms-user-select: none;\r\n");
      out.write("            user-select: none;\r\n");
      out.write("        }\r\n");
      out.write("        .popup .popuptext {\r\n");
      out.write("            visibility: hidden;\r\n");
      out.write("            width: 160px;\r\n");
      out.write("            background-color: #555;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            padding: 8px 0;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("            bottom: 125%;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            margin-left: -80px;\r\n");
      out.write("            opacity: 0.8;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .popup .show {\r\n");
      out.write("            visibility: visible;\r\n");
      out.write("            -webkit-animation: fadeIn 1s;\r\n");
      out.write("            animation: fadeIn 1s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @-webkit-keyframes fadeIn {\r\n");
      out.write("            from {opacity: 0;} \r\n");
      out.write("            to {opacity: 0.8;}\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes fadeIn {\r\n");
      out.write("            from {opacity: 0;}\r\n");
      out.write("            to {opacity:0.8 ;}\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .home {\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form id=\"sign_in_notice_form\">\r\n");
      out.write("\t\t<div id=\"background\">\r\n");
      out.write("        \t<img src=\"https://images.dailyhive.com/20190923083339/shutterstock_1508803526.jpg\">\r\n");
      out.write("    \t<header>\r\n");
      out.write("        \t<i class=\"fa fa-building-o\" aria-hidden=\"true\" style=\"font-size:30px;\"></i>\r\n");
      out.write("        \t<a href=\"hotel-mockup.html\" id=\"home\" class=\"home\"><h1>Fake Hotel</h1></a>\r\n");
      out.write("        \t<div class=\"flexExpand\"></div>\r\n");
      out.write("        \t<button type=\"submit\" class=\"button1\" onClick=\"setPageSignIn()\">Sign In</button>\r\n");
      out.write("        \t<input type=\"hidden\" name=\"signInPage\" id=\"sign_in_page\"/>\r\n");
      out.write("        \t<button type=\"submit\" class=\"button1\" onClick=\"setPageEvents()\">View Current Events</button>\r\n");
      out.write("        \t<input type=\"hidden\" name=\"eventPage\" id=\"events_page\"/>\r\n");
      out.write("    \t</header>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t<main>\r\n");
      out.write("    \t\t<div class=\"container\">\r\n");
      out.write("    \t\t\t<div class=\"center\">\r\n");
      out.write("    \t\t\t\t<p style=\"font-size:20px;margin-left: 17.5em;\">Success!</p>\r\n");
      out.write("    \t\t\t\t<p style=\"font-size:16px;margin-left: 5em;\">You've booked Room #");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${room_number}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("!</p>\r\n");
      out.write("    \t\t\t\t<p style=\"font-size:16px;margin-left: 5em;\">Thank you for booking with us!</p>\r\n");
      out.write("    \t\t\t\t<p style=\"font-size:16px;margin-left: 5em;\">Click the button below to return to the main page.</p>\r\n");
      out.write("    \t\t\t\t<button type=\"submit\" class=\"button1\" onClick=\"setPageMain()\" style=\"margin-left:23em;\">Return to Main Page</button>\r\n");
      out.write("    \t\t\t\t<input type=\"hidden\" name=\"mainPage\" id=\"main_page\"/>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</main>\r\n");
      out.write("    \t<footer>\r\n");
      out.write("        \t&copy; 2020 FakeHotel, a subsidiary of OtherFakeHotel. All rights reserved.\r\n");
      out.write("    \t</footer>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<script>\r\n");
      out.write("\tfunction setPageEvents() {\r\n");
      out.write("\t\tvar set_page = document.getElementById('events_page');\r\n");
      out.write("\t\tset_page.value = \"events_page\";\r\n");
      out.write("\t\tsubmit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction setPageSignIn() {\r\n");
      out.write("\t\tvar set_page = document.getElementById('sign_in_page');\r\n");
      out.write("\t\tset_page.value = \"sign_in\";\r\n");
      out.write("\t\tsubmit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction setPageMain() {\r\n");
      out.write("\t\tvar set_page = document.getElementById('main_page');\r\n");
      out.write("\t\tset_page.value = \"after_booking\";\r\n");
      out.write("\t\tsubmit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction submit() {\r\n");
      out.write("\t\tvar form = document.getElementById('sign_in_notice_form');\r\n");
      out.write("\t\tform.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
